model_config_list {
  config {
    name: "numeric_only"
    base_path: "/models/numeric_only"
    model_platform: "catboost"
  }
  config {
    name: "categorical_only"
    base_path: "/models/categorical_only"
    model_platform: "catboost"
  }
  config {
    name: "mixed_multiclass"
    base_path: "/models/mixed_multiclass"
    model_platform: "catboost"
  }
}
